version: '3.8'

services:
  mysql:
    image: mysql:8.0
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: mydb
      MYSQL_USER: myuser
      MYSQL_PASSWORD: mypassword
    ports:
      - "3306:3306"
    volumes:
      - mysql-data:/var/lib/mysql

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile.dev
    restart: always
    depends_on:
      - mysql
    ports:
      - "3001:3001"
    environment:
      - DB_HOST=mysql
      - DB_DATABASE=mydb
      - DB_USER=myuser
      - DB_PASSWORD=mypassword
    volumes:
      - ./backend:/app
      - /app/node_modules

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile.dev
    restart: always
    depends_on:
      - backend
    ports:
      - "3000:3000"
    environment:
      - NUXT_HOST=0.0.0.0
      - NUXT_PORT=3000
      - API_BASE_URL=http://backend:3001/api
    volumes:
      - ./frontend:/app
      - /app/node_modules

volumes:
  mysql-data:
